receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      load: {}
      memory: {}
      filesystem: {}
      network: {}
      process:
        mute_process_name_error: true

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  resource/drop_service_metadata:
    attributes:
      - key: service.name
        action: delete
      - key: service.version
        action: delete
      - key: deployment.environment
        action: delete
  attributes/log_attributes:
    actions:
      # Adiciona trace_id e span_id como atributos para correlação
      - key: trace_id
        action: insert
        from_context: trace_id
      - key: span_id
        action: insert
        from_context: span_id

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: "toq_server"
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
    headers:
      authorization: "${OTEL_EXPORTER_OTLP_TRACES_AUTH_HEADER}"
    tls:
      insecure: ${OTEL_EXPORTER_OTLP_TRACES_INSECURE}
  otlphttp/loki:
    endpoint: ${LOKI_OTLP_ENDPOINT}
    logs_endpoint: ${LOKI_OTLP_ENDPOINT}
    tls:
      insecure: ${LOKI_OTLP_INSECURE}
    headers:
      X-Scope-OrgID: "${LOKI_TENANT_ID}"
      Authorization: "${LOKI_OTLP_AUTH_HEADER}"

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource/drop_service_metadata, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, resource/drop_service_metadata, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource/drop_service_metadata, batch, attributes/log_attributes]
      exporters: [otlphttp/loki]
