receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      load: {}
      memory: {}
      filesystem: {}
      network: {}
      process:
        mute_process_name_error: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  resource/service_attributes:
    attributes:
      - key: service.name
        action: upsert
        value: ${OTEL_RESOURCE_SERVICE_NAME}
      - key: service.version
        action: upsert
        value: ${OTEL_RESOURCE_SERVICE_VERSION}
      - key: deployment.environment
        action: upsert
        value: ${OTEL_RESOURCE_ENVIRONMENT}
      - key: service.namespace
        action: upsert
        value: ${OTEL_RESOURCE_NAMESPACE}
  attributes/http_context:
    actions:
      - key: method
        action: upsert
        from_attribute: http.method
      - key: path
        action: upsert
        from_attribute: http.route
      - key: status
        action: upsert
        from_attribute: http.status_code
  attributes/log_attributes:
    actions:
      # Adiciona trace_id e span_id como atributos para correlação
      - key: trace_id
        action: insert
        from_context: trace_id
      - key: span_id
        action: insert
        from_context: span_id
      - key: user_id
        action: upsert
        from_attribute: user_id
  attributes/service_label:
    actions:
      - key: service
        action: upsert
        value: ${OTEL_RESOURCE_SERVICE_NAME}
  attributes/loki_labels:
    actions:
      - key: loki.attribute.labels
        action: upsert
        value: trace_id,span_id,request_id,method,path,status,user_id,service
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: "toq_server"
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
    headers:
      authorization: "${OTEL_EXPORTER_OTLP_TRACES_AUTH_HEADER}"
    tls:
      insecure: ${OTEL_EXPORTER_OTLP_TRACES_INSECURE}
  otlphttp/loki:
    endpoint: ${LOKI_OTLP_LOGS_ENDPOINT}
    tls:
      insecure: ${LOKI_OTLP_INSECURE}
    headers:
      X-Scope-OrgID: "${LOKI_TENANT_ID}"
      Authorization: "${LOKI_OTLP_AUTH_HEADER}"
  debug/logs:
    verbosity: detailed

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource/service_attributes, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, resource/service_attributes, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource/service_attributes, attributes/service_label, attributes/http_context, attributes/log_attributes, attributes/loki_labels, batch]
      exporters: [otlphttp/loki, debug/logs]
