apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      maxLines: 1000
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"([0-9a-f]+)"'
          datasourceUid: jaeger
          url: /trace/$${__value.raw}
          urlDisplayLabel: Jaeger Trace
    secureJsonData:
      httpHeaderValue1: fake
    editable: false
